### PR TITLE
Change marker for city size 3: red --> blue

### PR DESCRIPTION
**Pull request by tobetobi**
@yzemaze thx for the tool

the short extension might be helpful for gamers with color blindness (if useful feel free to change the link to your repo then i might delete my branch)

### CODE REVIEW

**Comment by yzemaze** [comment]
This either needs a config option or warrants a 2nd script as there are more things to be done for color blind friendliness: grey => black, maybe different ship & company border styles
As it’s niche^3 I’d like to get more input from affected people.

**Comment by tobetobi** [comment]
The city markers have been the most obvious issue to me (among others, there is no informaton about city size in the mouseover container). Further, I was interested in gerneral whether the ovals can be exhcanged that easy or not.

I agree that there may be further issues regarding others. Maybe these adjustements can be done more generic than I have proposed (such that peolple can choose their own replacements: e.g. some want to replace the green ovals or that instead of png files there can be css-city markers that can be defined within the code snippets by users themselves). Anyway, I will have to play the game to give more input from my point of view.

An extra config option or a second script would be nice.

thx so far.

**Comment by yzemaze** [comment]
No need for further action. I’m busy and nearly done.

**Review by yzemaze — COMMENTED** [review]
As far as I can see my solution covers your ideas.

**Comment by tobetobi** [comment]
Perfect, attaching new "level" attributes, that's what I was looking for ;-)

**Pull request closed without merging**
